### PR TITLE
Fix non-exhaustive pattern match in mkWeak'

### PR DESCRIPTION
**Pull request by mikusp**
I encountered a bug while experimenting with zero-copy diagrams rendering to Accelerate arrays. Minimal example is as follows:
```
module Main where

import Data.Array.Accelerate (Z(..), (:.)(..), Vector, use)
import Data.Array.Accelerate.CUDA (run)
import Data.Array.Accelerate.IO (fromVectors)
import Foreign (newForeignPtr, newArray, finalizerFree)
import Data.Vector.Storable (unsafeFromForeignPtr0)


main = do
    ptr <- newArray [1..(10::Int)]
    fptr <- newForeignPtr finalizerFree ptr
    let vec = unsafeFromForeignPtr0 fptr 10
        arr :: Vector Int
        arr = fromVectors (Z :. (10::Int)) vec
    print arr
    print $ run $ use arr
```

When run with accelerate packages from HEAD, I get this:
```
Array (Z :. 10) [1,2,3,4,5,6,7,8,9,10]
example: 
*** Internal error in package accelerate ***
*** Please submit a bug report at https://github.com/AccelerateHS/accelerate/issues
./Data/Array/Accelerate/Array/Memory/Table.hs:422:9: (makeWeakArrayData): Internal representation of Storable array has changed
```
However, it seems that while makeWeakArrayData should work with PlainForeignPtr-type of ForeignPtr, it was omitted from the pattern match. With proposed change, example program runs to completion.

### CODE REVIEW

**Comment by mikusp** [comment]
Now I see it's not as simple as I thought. Package `vector` allocates new vectors using `mallocPlainForeignPtr` function, so they are almost guaranteed to have a PlainPtr inside. The problem is, PlainPtr does not carry an IORef with finalizers so it's not possible to make a Weak with MutVar# as a key.

Following program will trigger this case:
```
module Main where

import Data.Array.Accelerate (Z(..), (:.)(..), Vector, use)
import Data.Array.Accelerate.CUDA (run)
import Data.Array.Accelerate.IO (fromVectors)
import Data.Vector.Storable (generate)


main = do
    let vec = generate 10 (const 1)
        arr :: Vector Int
        arr = fromVectors (Z :. (10::Int)) vec
    print arr
    print $ run $ use arr
```

**Comment by robeverest** [comment]
@mikusp Yes, it seems I made some assumptions about the way `vector` uses `ForeignPtr`s that aren't always true. 

Fortunately, I do have a solution to this involving the `Lifetime`s I introduced for managing our other resources. It should also make the whole thing a bit neater and less fragile to changes in `vector`. I'm a bit busy with other things at the moment, but I should hopefully get to it later in the week.

**Comment by mikusp** [comment]
Great to hear that! I'll close this pull request and wait for the proper fix.

**Comment by robeverest** [comment]
@mikusp Sorry for the delay, but I've pushed a fix for this now.

**Pull request closed without merging**
