### PR TITLE
Fix OSX specific CI issues

### PR DESCRIPTION
**Pull request by LaurentRDC**
This PR fixes OSX-specific CI issues which don't happen on other platforms.

This PR will remain in draft state until I can figure out what's wrong -- I don't have Apple hardware to test locally

### CODE REVIEW

**Comment by tomsmeding** [comment]
Thanks for the work! We'll have a look, some of us have Apple hardware to test on.

**Comment by LaurentRDC** [comment]
@tomsmeding If you approve this workflow, I can work at it over the weekend

**Comment by tomsmeding** [comment]
I'm seeing some capstone-related errors in the macos CI; I'm currently upgrading tracy, and the new tracy version downloads and builds its own capstone. Let's see if that works better.

**Comment by tomsmeding** [comment]
It turns out that the `+ACC` flag parsing doesn't work on mac with your fix; see the commit description. I tested this on a mac and this does seem to work.

**Comment by tomsmeding** [comment]
Ah meh this CI run would be pointless anyway because it's going to succeed for macos-release and fail for macos-debug for Tracy reasons.

**Comment by LaurentRDC** [comment]
Thanks for taking care of this!

**Pull request merged**
