### PR TITLE
Add an annotation system and source mapping support

### PR DESCRIPTION
**Pull request by robbert-vdh**
**Description**  
This (draft) PR adds source mapping to Accelerate programs by extending Accelerate's abstract syntax with a new annotation system. That source information can later be used in the `accelerate-llvm` backend to include debug symbols in the compiled programs and to add more context for the Tracy client. There are also some placeholders for compiler optimization instructions which will be used in a later PR. More details on the current implementation status can be found in doc comment at the top of the new `Data.Array.Accelerate.Annotations` module. I will also submit a PR that adds the required changes to make `accelerate-llvm` compile again shortly after this.

There are still lots of todos and fixmes littered around the code with open questions I'm not sure what the correct answers to are. I'm looking for feedback on the general implementation, but specifically also on some of the following:

- The pretty printer right now just prints a node's source information and optimization flags after the node if those things are available, adding parentheses where needed. This was the simplest way to get something useable for debugging, but this will probably need some more thought. This PR also changes the pretty printer's verbose configuration option into a numerical value for multiple verbosity levels. We would need to decide on what information is relevant to show on the default verbosity level and what is not. For instance, the source location of a let-binding is probably not very useful, and printing the source location for every expression-level variable will likely result in a lot of clutter.
- Either this PR or a next PR will need to add a value argument to the `-dverbose` option for the above mentioned new verbosity levels. Right now the default is `Normal` aka level 1, and specifying `-dverbose` will change the verbosity to `Verbose` aka level 2.
- There's a bit of ambiguity on how annotations should be propagated through the simplification and the fusion transformation passes. Right now there will definitely be some cases were I did the wrong thing. In most cases this could probably also be spotted by printing programs with `-dverbose` enabled, which also shows the end of the source region and how many more disjoint source regions an AST node has.
- I haven't modified the AST hashing and matching implementations to consider annotations yet because I wasn't sure what the correct approach would be. It seems sensible to me to include both source locations and optimization flags in the hashing, and to only consider optimization flags in the matching. Does that make any sense? I'd assume being too specific here would risk missing out on sensible optimizations in the simplification pass, while not being specific enough could change a program's meaning by adding optimization flags to nodes that wouldn't normally have them (right now this is not an issue of course since those flags do not yet do anything). **EDIT: For now I went with incorporating both locations and flags in the hashes, and only matching the flags when matching two AST nodes for equality.**
- Source mapping is done through three mechanisms. The `Data.Array.Accelerate.Annotations` module contains a more detailed explanation, but the short version is that `sourceMap` uses the current GHC call stack (`HasCallStack`), `sourceMapRuntime` uses DWARF debug symbols, and `sourceMapPattern` is a special case of the first one for pattern synonyms. The `sourceMap` variant will work on any GHC version, but the others will not. This means that some (expression level) AST nodes will never have any source mapping information attached to them.

  - `sourceMapPattern` only works on GHC 9.2.0 and up because of GHC bug [#19289](https://gitlab.haskell.org/ghc/ghc/-/issues/19289). To prevent inconsistencies pattern synonyms will not have any source mapping information at all on lower GHC versions. I haven't been able to test this within Accelerate since some of Accelerate's dependencies haven't been updated for GHC 8.2 yet, but I have verified that the implementation works correctly in a standalone application.
  - `sourceMapRuntime` relies on GHC being compiled with `libdw` support (`--enable-dwarf-unwind`) and will also produce empty source mapping annotations if this is not the case. In practice, this feature is never available unless you specifically compiled GHC yourself to use this feature or if you installed the 'Debian XX (with DWARF support)' bindist from the haskell.org website. And if DWARF support is available, then the output will require a lot of filtering because the DWARF stack unwinding goes all the way back to some RTS internals and the base library. Right now I've simply disabled this entirely because it's not very important (it's only used for some prelude type classes like `Num`, `Floating`, `Bounded`, `Semigroup` and `Monoid`). If GHC's DWARF support ever improves, it should be trivial to add this back in.

**Motivation and context**  
This opens the door to better debugging and profiling facilities for Accelerate. And later this annotation system can be reused to allow programmer-specified optimizations on Accelerate programs. This can for instance help with situations where the sharing of trivial array expressions would prevent fusion by specifying that those terms should always be inlined.

**How has this been tested?**  
This has been developed and tested with `stack-8.10.yaml` and `stack-9.0.yaml` on Arch Linux. The main way this was tested was by simply printing simple Accelerate programs and looking at the pretty printer output. There's also a new test suite with unit tests that test some specific algorithms and properties of the transformation pipeline's output.

**Types of changes**  
What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

**Checklist**  
Go over all the following points, and put an `x` in all the boxes that apply. If you're unsure about any of these, don't hesitate to ask. We're here to help!

- [ ] My code follows the code style of this project - This will need some reformatting. Since Accelerate doesn't have a styleguide or a formatter configuration I mostly stuck with the original style when I modified something, and in the new `Data.Array.Accelerate.Annotations` module I more or less just let Brittany do its thing.
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes - See above
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by robbert-vdh** [comment]
I got fed up with Stack getting stuck in broken states every other hour so I made some small changes in eff4117e13b562a20d96ecd88c8506af6e88acb2...3500acb26cb5ae0646a51ef1537212877a94fb09 so Accelerate compiles again with regular Cabal (which now always builds from an sdist even when using a `source-repository-package`). The doctests module wasn't marked as generated, and a lot of Tracy files were missing from that sdist. Should I submit a separate PR for these changes? So for reference, I'm now building `accelerate-llvm` with this `cabal.project`:

```cabal
packages: accelerate-llvm
          accelerate-llvm-native
          accelerate-llvm-ptx

source-repository-package
    type: git
    location: https://github.com/robbert-vdh/accelerate.git
    tag: 3500acb26cb5ae0646a51ef1537212877a94fb09
    -- Cabal builds from an sdist, and `accelerate.cabal` references files that
    -- don't exist on a fresh clone. The next cabal version does this
    -- automatically.
    -- XXX: For some reason cabal just stops when the command returns 0? So
    --      negating this seems to 'work'
    post-checkout-command: bash -c "! git submodule update --init --recursive"

source-repository-package
    type: git
    location: https://github.com/llvm-hs/llvm-hs.git
    tag: 351683ed1c2f6b329e62439d42a158b1d804b846
    subdir: llvm-hs llvm-hs-pure

package accelerate
    flags: +debug
```

**Review by tmcdonell — COMMENTED** [review]
so many changes! looking great so far :D

**Comment by robbert-vdh** [comment]
I've gone through the obsolete todo comments and reformatted the `Data.Array.Accelerate.Annotations` module (some other places still need reformatting, but I where possible wanted to avoid modifying more lines in this PR than were strictly necessary). The todo comments that remain are all things I'm not sure about. There are still no tests though since I'm not yet sure what the correct way to test this is. Testing whether there are source mapping annotations is one thing, but ideally you'd want to check if an AST (both the smart ASTs before transformations and the delayed fused ASTs) contain the _correct_ annotations.

**Comment by robbert-vdh** [comment]
I've added a new test suite to Accelerate with some tests for a couple of the new algorithms and a basic test for the transformation pipeline's output. I'll add some more tests later when if I can come up with more useful and easily testable properties. It might also be worthwhile to move some of the general non-backend specific Accelerate tests that now ended up in nofib to this test suite later.

**Comment by robbert-vdh** [comment]
I'll close this and https://github.com/AccelerateHS/accelerate-llvm/pull/74 since these are incomplete versions of the features anyways. The final version can be found in these two branches:

https://github.com/robbert-vdh/accelerate/tree/feature/force-inline
https://github.com/robbert-vdh/accelerate-llvm/tree/feature/tracy-annotations

**Pull request closed without merging**
