### PR TITLE
Add NOINLINE pragma to `bound`

### PR DESCRIPTION
**Pull request by bgamari**
This function is quite difficult to optimize due to the deep recursion
that is can generate with high-dimensional arrays. If we let 'next' be
inlined into each alternative of the cases above the size of this
function on an n-dimensional array will grow as 7^n. This quickly causes
GHC's head to explode.

See [GHC Trac #10491](https://ghc.haskell.org/trac/ghc/ticket/10491) for more details.

### CODE REVIEW

**Comment by tmcdonell** [comment]
Thanks! Following the issue has been enlightening.

**Comment by tmcdonell** [comment]
Seems that 7.10 still has some problems and is timing out travis, but we'll have to try and track that down in a separate issue.

**Comment by bgamari** [comment]
Interesting, 7.10.1 finishes in about 5 minutes on my machine with this patch. Have you reproduced this result outside of Travis?

**Comment by tmcdonell** [comment]
Actually with or without the patch accelerate by itself completes in roughly the same time for me. GHC (7.10.1) does use 900 MB RAM though (about 950 without the patch), so I guess that is the issue; some of the travis hosts must be quite lean.

At least with the patch we can compile Slice.hs and similar on real (non-travis) machines.

**Pull request merged**
