### PR TITLE
(WIP. Do not merge.) New streaming implementation 

### PR DESCRIPTION
**Pull request by robeverest**
I've created this PR to track the now substantial differences between master and the current version of streaming accelerate. Before even considering a merge, the following needs to happen, in roughly this order.
- [x] Fusion transform does not eliminate some, seemingly obvious, forms of dead code.
- [x] Need to fuse through tuples better than we did in the FHPC version of streaming. Have a couple ideas for this. Needs further investigation. **Have a generally very useful solution**
- [x] Regular streams? Should we still try to support them or just assume all streams are irregular and hope optimisation will take care of it in the cases they are regular? **Changing the nested array representation to track regularity, as well as extending fusion to work through tuples in all cases (See comments in Fusion.hs), thus far seems to be a very good solution to this problem, giving us both regular and irregular streams without any additional cost to regular streams.**
- [x] Support for streaming from at least one backend. A lot easier to do than the old streaming implementation.  **Have a working version of the CUDA backend [here](https://github.com/AccelerateHS/accelerate-cuda/tree/streaming). Will likely need to have its scheduling tweaked based on how larger examples perform.**
- [x] ~~Rebase and squash? Might want to get rid of all the commits containing failed experiments.~~

What still needs to be done before Haskell Symposium deadline:
- [ ] Streaming in from lists needs to be fixed up. Non-trivial examples are likely to require this.
- [x] `mapAccumFlat` and `foldSeqFlatten` are not general enough. Need a slightly different version. Maybe go back to something closer to a `scan` or a `fold` with a semi-associative operator? **Have a more general operation in `mapBatch`. Not entirely happy with this, both in terms of its name and its semantics, but it's general enough to implement the MNIST example. Can revise it later depending on how it ends up getting used.**
- [ ] A regular example (probably neural networks)
- [ ] An irregular example

What may need to be done depending on examples:
- [ ] A sequence computation that has multiple outputs, and hence can't be fused into a single array computation, may not always have its irregularity flags erased by optimisation. This should be fixable, just need to add some special sauce to fusion. The same is true for uses of `Awhile`.
- [ ] Sequence invariant code motion

What can get punted till after the deadline:
- [ ] Streaming out -- i.e. Lazily piping a stream out from Accelerate. Can be done without too much hassle, but should try to do it such that we preserve the property that backends are completely oblivious to our nested array representation.  
- [ ] General clean-up and more documentation for the hairier parts of vectorisation and fusion.
- [ ] Intense interrogation from the warning police.

### CODE REVIEW

**Comment by tmcdonell** [comment]
On the last point:
 - Failed experiments are still positive results. I would advocate include _more_ documentation pointing to the failure as a driver for the chosen design. We don't want to make the same mistakes again later.
 - Squashing a commit this large destroys far too much history, don't do that.
 - Don't rebase either. If you are trying to git-bisect, a merge commit is a valid point of reference and might just be the point a bug snuck in. Also your rebase is basically guaranteed to fail, so save yourself the heartache.

**Comment by tmcdonell** [comment]
I also see that you guys are totally failing to use travis effectively ...

**Comment by robeverest** [comment]
The travis failures in the past were nearly all to that GHC thing that caused compilation to take many hours. Now that we're passed that, hopefully we can use travis properly.

**Comment by tmcdonell** [comment]
oh right, I remember that! good times... \:

**Comment by tmcdonell** [comment]
woo! :+1:

**Pull request merged**
